# variables
DOCKER_ADDRESS = hub.pingcap.net
DOCKER_NAME = yejunchen/release-dashboard
DOCKER_FILE = ./Dockerfile

# local commands
help:
	@echo "make build : build all binaries"
	@echo "make run : build all binaries and run"
	@echo "make clean : clear all temporary files and folders generated by the 'make build' or 'make run'"

build:
	yarn install && \
	yarn build

clean:
	@rm -rf build/

run:
	yarn start

# remote commands
docker:
	docker build -f ${DOCKER_FILE} -t ${DOCKER_NAME} .
	docker tag ${DOCKER_NAME}:latest ${DOCKER_ADDRESS}/${DOCKER_NAME}:latest
	docker push ${DOCKER_ADDRESS}/${DOCKER_NAME}:latest

# register phony targets
.PHONY: build run clean help
.PHONY: docker
